const ERROR_CODE = {
  INVALID_INPUT: 'INVALID_INPUT',
  INSUFFICIENT_CREDIT: 'INSUFFICIENT_CREDIT',
  CLAUDE_API_ERROR: 'CLAUDE_API_ERROR',
  SWEETBOOK_API_ERROR: 'SWEETBOOK_API_ERROR',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
}
module.exports = ERROR_CODE
