const ORDER_STATUS = {
  PAID: 20,
  PDF_READY: 25,
  CONFIRMED: 30,
  IN_PRODUCTION: 40,
  PRODUCTION_COMPLETE: 50,
  SHIPPED: 60,
  DELIVERED: 70,
  CANCELLED: 80,
  CANCELLED_REFUND: 81
}

module.exports = ORDER_STATUS
